function prettify(hgca,hbar,hlegend)
% PRETTIFY sets standard plot appearance
%    PRETTIFY(hgca,hbar,hlegend) sets standard plot appearance, by
%    changing properties of the axis, the colorbar, and the legend
%    box. Only first one is a mandatory parameter
%
hTitle=get(hgca,'title');
hXLabel=get(hgca,'xlabel');
hYLabel=get(hgca,'ylabel');

set(hgca,...
    'FontName', 'Helvetica'   , ...
    'Box'         , 'on'      , ...
    'TickDir'     , 'out'      , ...
    'TickLength'  , [.012 .012] , ...
    'XMinorTick'  , 'on'      , ...
    'YMinorTick'  , 'on'      , ...
    'XGrid'       , 'off'     , ...
    'YGrid'       , 'off'     , ...
    'XColor'      , [.2 .2 .2], ...
    'YColor'      , [.2 .2 .2], ...
    'FontSize'    , 12        , ... 
    'LineWidth'   , 1.5         );

set(hTitle,...
    'FontName'  , 'AvantGarde', ...
    'FontSize'  , 14          , ...
    'FontWeight', 'bold'      );

set([hXLabel, hYLabel],       ...
    'FontName', 'Helvetica', ...
    'FontSize', 14          );

if exist('hbar','var')
  set(hbar,'fontsize',12);
  set(get(hbar,'xlabel'),'fontsize',14);
  set(get(hbar,'ylabel'),'fontsize',14);
end

if exist('hlegend','var')
  set(hlegend             , ...
      'FontSize'   , 12           );
end

%